### ISSUE TITLE
Implementing $focus

### ISSUE THREAD

**Issue by jkiddo** [Gravitate-Health/focusing-interfaces#1]
We need the focusing interface to implement the operation as defined on http://build.fhir.org/ig/hl7-eu/gravitate-health/OperationDefinition-calculate.html

**Comment by jkiddo** [comment]
FYI @gcangioli

**Comment by jkiddo** [comment]
Be aware that IPS is v4 where ePI is v5

**Comment by jkiddo** [comment]
@amedranogil any news on this?

**Comment by abelmarm** [comment]
Hi @jkiddo, sorry I forgot to answer. I talked with Giorgio at the Connectathon and explained that the operation is already implemented, for now it is in the [MedicationInfo G-Lens](https://github.com/Gravitate-Health/MedicationInfo) module. More specifically in the [controller](https://github.com/Gravitate-Health/MedicationInfo/blob/ebced7715bcb01cc7b79e9d74c0b4f8a3a1f90af/src/controllers/med-information.controller.ts#L124). It sends the data to the focusing module and it computes it, this may change in MVP2 to directly use the focusing interface.

**Comment by jkiddo** [comment]
Great - when can we expect you guys to have the `calculate`operation up and running?

**Comment by jkiddo** [comment]
and @abelmarm / @amedranogil also have a look at https://github.com/hl7-eu/gravitate-health/issues/4

**Comment by abelmarm** [comment]
> Great - when can we expect you guys to have the `calculate`operation up and running?

It is already running with a very basic functionality, for now it just replies with some added JSON values about age, and gender

> and @abelmarm / @amedranogil also have a look at [hl7-eu/gravitate-health#4](https://github.com/hl7-eu/gravitate-health/issues/4)

Sure!, will do

**Comment by jkiddo** [comment]
@abelmarm do you have an url of the instance running?

**Comment by abelmarm** [comment]
@jkiddo I will send you the Postman collection of the request with the authentication via email

**Comment by jkiddo** [comment]
@amedranogil / @abelmarm the operation has been renamed to https://build.fhir.org/ig/hl7-eu/gravitate-health/OperationDefinition-focus.html

**Comment by jkiddo** [comment]
@amedranogil / @abelmarm I have provided you with a full skeleton implementation here: https://github.com/trifork/gravitate-health-lens
